//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace multiply {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StaticResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StaticResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("multiply.StaticResources", typeof(StaticResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column argument should be valid integer.
        /// </summary>
        internal static string ColumnArgument {
            get {
                return ResourceManager.GetString("ColumnArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format argument should be valid output format: csv, html, console.
        /// </summary>
        internal static string FormatArgument {
            get {
                return ResourceManager.GetString("FormatArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Correct way to run the application:
        ///multiply.exe rows [cols] [output-format]
        ///For example: 
        ///multiply.exe 4 5 csv 
        ///multiply.exe 10 html
        ///Valid values for output-format are console, csv and html.
        ///Valid values for rows and cols are integers between 1 and 20..
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No arguments provided..
        /// </summary>
        internal static string NoArguments {
            get {
                return ResourceManager.GetString("NoArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid values for rows and cols are integers between 1 and 20.
        /// </summary>
        internal static string OutOfRange {
            get {
                return ResourceManager.GetString("OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row argument should be valid integer.
        /// </summary>
        internal static string RowArgument {
            get {
                return ResourceManager.GetString("RowArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second argument is invalid. It should be columns number or output format.
        /// </summary>
        internal static string SecondArgument {
            get {
                return ResourceManager.GetString("SecondArgument", resourceCulture);
            }
        }
    }
}
